/*

 DECO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __deco_h_INCLUDE
#define __deco_h_INCLUDE

#define deco1Width 6
#define deco1Height 6
#define deco1Bank 0

extern const unsigned char deco1[];

#endif

/* End of DECO.H */
