/*

 DECO3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __deco3_h_INCLUDE
#define __deco3_h_INCLUDE

#define deco3Width 6
#define deco3Height 6
#define deco3Bank 0

extern const unsigned char deco3[];

#endif

/* End of DECO3.H */
