/*

 DECO5.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define deco5Width 4
#define deco5Height 4
#define deco5Bank 0

const unsigned char deco5[] =
{
  0x04,0x07,0x06,0x2D,0x24,0x15,0x12,0x13,0x30,0x25,
  0x0E,0x33,0x2E,0x1D,0x1C,0x1F
};

/* End of DECO5.C */
