/*

 DECO4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __deco4_h_INCLUDE
#define __deco4_h_INCLUDE

#define deco4Width 6
#define deco4Height 6
#define deco4Bank 0

extern const unsigned char deco4[];

#endif

/* End of DECO4.H */
