#pragma bank 1
/*

 ENEMYDROPS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Drops[] =
{
  0x66,0x66,0xFF,0x99,0xFF,0x81,0xFF,0x81,
  0xFF,0x81,0x7E,0x42,0x3C,0x24,0x18,0x18,
  0x07,0x07,0x0F,0x09,0x07,0x05,0x0A,0x0A,
  0x10,0x10,0xE0,0xE0,0xA0,0xE0,0x60,0x60
};

/* End of ENEMYDROPS.C */
