/*

 KEY.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Key[] =
{
  0x38,0x38,0x44,0x7C,0xFB,0x97,0xEC,0xAB,
  0xFF,0x93,0x7C,0x44,0x38,0x38,0x00,0x00,
  0x00,0x00,0x00,0x00,0xFF,0xFF,0x01,0xFF,
  0xFD,0xDF,0x77,0x55,0x77,0x77,0x00,0x00
};

/* End of KEY.C */
