/*

 WPN_ARROW.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Arrow[] =
{
  0x10,0x10,0x38,0x28,0x7C,0x7C,0x10,0x10,
  0x10,0x10,0x38,0x38,0x54,0x7C,0x6C,0x6C,
  0x00,0x00,0xC4,0xC4,0xA6,0xE6,0x7F,0x7D,
  0xA6,0xE6,0xC4,0xC4,0x00,0x00,0x00,0x00
};

/* End of WPN_ARROW.C */
