/*

 DUNGEONTILES2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 52

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __DungeonTiles2_h_INCLUDE
#define __DungeonTiles2_h_INCLUDE

/* Bank of tiles. */
#define Dungeon2Bank 0
/* Start of tile array. */
extern const unsigned char DungeonTiles2[];

#endif

/* End of DUNGEONTILES2.H */
