#include <gb/gb.h>
#include "../scripts/generate_dungeon.h"

/*

 MINIMAP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __minimap_h_INCLUDE
#define __minimap_h_INCLUDE

/* Bank of tiles. */
#define MinimapBank 0
/* Start of tile array. */
extern const unsigned char Minimap[];
extern const unsigned char map_menu[];
extern const unsigned char stats_menu[];
extern uint8_t current_location;
extern uint8_t doors[4][4];
extern uint8_t map[4][4];
extern uint8_t current_location;
extern Coords player_coords;

void set_map_menu() BANKED;
void empty_map_tiles() BANKED;
#endif

/* End of MINIMAP.H */
