/*

 NOEXITROOM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __noexitroom_h_INCLUDE
#define __noexitroom_h_INCLUDE

#define NoExitWidth 20
#define NoExitHeight 18
#define NoExitBank 0

extern const unsigned char NoExit[];

#endif

/* End of NOEXITROOM.H */
