/*

 DUNGEON.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Dungeon_h_INCLUDE
#define __Dungeon_h_INCLUDE

#define room1Width 20
#define room1Height 18
#define room1Bank 0

extern const unsigned char room1[];
extern const unsigned char room2[];
extern const unsigned char room3[];
extern const unsigned char room4[];
extern const unsigned char room5[];
extern const unsigned char room6[];
extern const unsigned char room7[];
extern const unsigned char room8[];
extern const unsigned char room9[];
extern const unsigned char room10[];
extern const unsigned char room11[];
extern const unsigned char room12[];
extern const unsigned char room13[];
extern const unsigned char room14[];
extern const unsigned char room15[];

#endif

/* End of DUNGEON.H */
