/*

 GAMEOVER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\prova\textblack.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __GameOver_h_INCLUDE
#define __GameOver_h_INCLUDE

#define GameOverWidth 20
#define GameOverHeight 18
#define GameOverBank 0

extern const unsigned char GameOver[];

#endif

/* End of GAMEOVER.H */
