/*

 INTROSLIDE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\daringbaby\Tirocinio\Slide2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __IntroSlide2_h_INCLUDE
#define __IntroSlide2_h_INCLUDE

#define IntroSlide2Width 20
#define IntroSlide2Height 18
#define IntroSlide2Bank 0

extern const unsigned char IntroSlide2[];

#endif

/* End of INTROSLIDE2.H */
