/*

 INTROSLIDE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\prova\introslide1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __IntroSlide1Map_h_INCLUDE
#define __IntroSlide1Map_h_INCLUDE

#define IntroSlide1Width 20
#define IntroSlide1Height 18
#define IntroSlide1Bank 0

extern const unsigned char IntroSlide1[];

#endif

/* End of INTROSLIDE1.H */
