/*

 INTROSLIDE3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\daringbaby\Tirocinio\Slide3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __IntroSlide3_h_INCLUDE
#define __IntroSlide3_h_INCLUDE

#define IntroSlide3Width 20
#define IntroSlide3Height 18
#define IntroSlide3Bank 0

extern const unsigned char IntroSlide3[];

#endif

/* End of INTROSLIDE3.H */
