/*

 ROOM9.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room9_h_INCLUDE
#define __room9_h_INCLUDE

#define room9Width 20
#define room9Height 18
#define room9Bank 0

extern const unsigned char room9[];

#endif

/* End of ROOM9.H */
