/*

 ROOM2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\DungeonTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __room2_h_INCLUDE
#define __room2_h_INCLUDE

#define room2Width 20
#define room2Height 18
#define room2Bank 0

extern const unsigned char room2[];

#endif

/* End of ROOM2.H */
