/*

 TITLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Utente\Desktop\Tirocinio\Giochi Tirocinio\Tales of Lithos\src\tiles\Titlescreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Title_h_INCLUDE
#define __Title_h_INCLUDE

#define TitleWidth 20
#define TitleHeight 18
#define TitleBank 0

extern const unsigned char Title[];

#endif

/* End of TITLE.H */
